name: Deploy Docs
on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - .github/workflows/deploy-docs.yaml
      - fastagency/__about__.py

permissions:
  contents: write
jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install -e ".[dev]"
      - run: ls -lah docs/docs/en/api/fastagency/studio
      - run: ./scripts/build-docs.sh
      - run: ls -lah docs/docs/en/api/fastagency/studio
      - run: ls -lah docs/site/api/fastagency/studio
      - run: echo "Dummy change to trigger CI"
      - run: echo "VERSION=$(python3 -c 'from importlib.metadata import version; v=version("fastagency"); print(".".join(v.split(".")[:2]) if "dev" not in v else v[:9])')" >> $GITHUB_ENV
      - run: echo "IS_RC=$(python3 -c 'from importlib.metadata import version; print("rc" in version("fastagency"))')" >> $GITHUB_ENV
      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - run: echo $VERSION
      - run: echo $IS_RC
      - run: ls -lah docs/site/api/fastagency/studio
      - run: |
          if [ "$IS_RC" == "False" ]; then
            ls -lah docs/site/api/fastagency/studio
            cd docs && mike deploy -F mkdocs.yml --update-aliases $VERSION latest
            mike set-default --push --allow-empty -F mkdocs.yml latest
            ls -lah site/api/fastagency/studio
          else
            cd docs && mike deploy --push -F mkdocs.yml --update-aliases $VERSION
          fi
